import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Itinerary, PlannerInput } from '../types';

// --- THEME & CONFIGURATION ---
const theme = {
  colors: {
    primary: [5, 150, 105] as [number, number, number],
    primaryLight: [236, 253, 245] as [number, number, number],
    textMain: [17, 24, 39] as [number, number, number],
    textLight: [107, 114, 128] as [number, number, number],
    accent: [249, 115, 22] as [number, number, number],
    border: [229, 231, 235] as [number, number, number],
    
    dayBadgeBg: [224, 242, 241] as [number, number, number],
    dayBadgeText: [0, 105, 92] as [number, number, number],
    tagBg: [243, 244, 246] as [number, number, number],
    costBg: [249, 250, 251] as [number, number, number],
    hotelBg: [240, 253, 244] as [number, number, number],
    hotelText: [21, 128, 61] as [number, number, number],
  },
  fonts: {
    header: 'helvetica',
    body: 'helvetica'
  }
};

// Helper function to safely convert anything to a String
const safeString = (value: any): string => {
  if (!value) return "";
  
  if (typeof value === 'string') return value;
  
  if (Array.isArray(value)) {
    return value.map(item => {
      if (typeof item === 'string') return item;
      if (typeof item === 'object' && item !== null) {
        return item.description || item.activity || item.name || Object.values(item).join(" - ");
      }
      return String(item);
    }).join("\n");
  }
  
  if (typeof value === 'object' && value !== null) {
     return value.description || value.text || Object.values(value).join(" ");
  }
  
  return String(value);
};

export const generatePDF = (itinerary: Itinerary, input: PlannerInput, activityOverrides?: Record<number, any[]>, hotelOverrides?: Record<number, any> ) => {
  const planToPrint = JSON.parse(JSON.stringify(itinerary)); // Original copy

    if (planToPrint.days) {
        const totalDays = planToPrint.days.length;
        planToPrint.days = planToPrint.days.map((day: any, index: number) => {
            const newDay = { ...day };
            
            // User Activities overrides
            if (activityOverrides && activityOverrides[index]) {
                newDay.activities = activityOverrides[index];
            }
            
            // User Hotels overrides
            if (hotelOverrides && hotelOverrides[index]) {
                newDay.accommodation = hotelOverrides[index];
            }

            // Remove accommodation for the last day
            if (index === totalDays - 1) {
                delete newDay.accommodation;
                if (newDay.estimatedCost) {
                    newDay.estimatedCost.accommodation = 0;
                }
            }

            return newDay;
        });
    }
    
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 14;
  let yPos = 0;

  // --- HELPERS ---
  const drawSidebar = () => {
    doc.setFillColor(0, 66, 49);
    doc.rect(0, 0, 60, pageHeight, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont(theme.fonts.header, 'bold');
    doc.context2d.save();
    doc.context2d.translate(40, pageHeight - 40);
    doc.context2d.rotate(-Math.PI / 2);
    doc.text("LANKAVIBE PLANNER", 0, 0);
    doc.context2d.restore();
  };

  const addPageHeader = (pageNumber: number) => {
    doc.setFillColor(0, 66, 49);
    doc.rect(0, 0, pageWidth, 15, 'F');
    
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.setFont(theme.fonts.header, 'bold');
    doc.text("Trip Itinerary", margin, 10);
    doc.setFont(theme.fonts.body, 'normal');
    doc.text(`Page ${pageNumber}`, pageWidth - margin, 10, { align: 'right' });
  };

  const addFooter = () => {
    const str = `Generated by LankaVibe AI | ${new Date().toLocaleDateString()}`;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(str, pageWidth / 2, pageHeight - 8, { align: 'center' });
  };

  const checkPageBreak = (neededHeight: number) => {
    if (yPos + neededHeight > pageHeight - 15) {
      doc.addPage();
      const pageCount = doc.getNumberOfPages();
      addPageHeader(pageCount);
      addFooter();
      yPos = 25;
      return true;
    }
    return false;
  };

  // --- CARD DRAWING FUNCTION ---
  const drawDayCard = (day: any, index: number) => {
    const cardWidth = pageWidth - (margin * 2);
    const contentX = margin + 35; 

    // Extract Description
    let rawDesc = day.dayDescription || day.description || day.detailedActivities || day.summary || day.notes;
    let descText = safeString(rawDesc);
    if (!descText || descText.trim() === "") {
        descText = "Explore and enjoy the sights of this beautiful location.";
    }
    
    // FIX: Remove unexpected hard line breaks from the AI data so it forms a clean paragraph
    descText = descText.replace(/\r\n|\n|\r/g, ' ').replace(/\s+/g, ' ').trim();

    // FIX: Must set the exact font size and style BEFORE splitTextToSize to calculate the width correctly!
    doc.setFontSize(9);
    doc.setFont(theme.fonts.body, 'normal');
    
    const descLines = doc.splitTextToSize(descText, cardWidth - 45);
    const descHeight = descLines.length * 5;

    const activities = Array.isArray(day.activities) ? day.activities : [];
    
    // Calculate tags (activities) height based on bullet point list
    const tagsHeight = activities.length > 0 ? (activities.length * 6) + 4 : 0;

    const costBoxHeight = 18;
    
    // Calculate Hotel Box Height dynamically based on details
    let hotelBoxHeight = 0;
    if (day.accommodation) {
        hotelBoxHeight = 20; 
        if (typeof day.accommodation === 'object' && day.accommodation.description) {
            hotelBoxHeight = 28; 
        }
    }
    
    const extraSpaceForDistance = day.travelDistance ? 6 : 0;
    const cardHeight = 15 + extraSpaceForDistance + descHeight + tagsHeight + costBoxHeight + hotelBoxHeight + 15;

    checkPageBreak(cardHeight + 5);
    const actualY = yPos; 

    // Background
    doc.setDrawColor(230, 230, 230);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(margin, actualY, cardWidth, cardHeight, 3, 3, 'FD');

    // Badge
    doc.setFillColor(...theme.colors.dayBadgeBg);
    doc.roundedRect(margin + 5, actualY + 5, 25, 30, 2, 2, 'F');
    doc.setTextColor(...theme.colors.dayBadgeText);
    doc.setFontSize(8);
    doc.text(`DAY ${day.day}`, margin + 17.5, actualY + 15, { align: 'center' });
    doc.setFontSize(14);
    doc.text(`${index + 1}`, margin + 17.5, actualY + 25, { align: 'center' });

    // Location
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont(theme.fonts.header, 'bold');
    doc.text(safeString(day.location), contentX, actualY + 12);

    let contentY = actualY + 18;

    // Travel Distance
    if (day.travelDistance) {
        doc.setFontSize(9);
        doc.setFont(theme.fonts.header, 'bold');
        doc.setTextColor(...theme.colors.primary);
        doc.text(`Travel: ${day.travelDistance} driving`, contentX, contentY);
        contentY += 6;
    }

    // Description (Font is already set correctly above)
    doc.setTextColor(...theme.colors.textLight);
    doc.setFontSize(9);
    doc.setFont(theme.fonts.body, 'normal');
    doc.text(descLines, contentX, contentY);
    contentY += descHeight + 4;

    // Tags (Activities) as Bullet Points (Attractive List)
    if (activities.length > 0) {
        let listY = contentY;
        doc.setFontSize(9);
        doc.setFont(theme.fonts.header, 'bold');
        
        activities.forEach((act: any) => {
          const text = safeString(typeof act === 'string' ? act : act.name);
          
          // Custom Bullet Point
          doc.setFillColor(...theme.colors.accent);
          doc.circle(contentX + 2, listY - 1, 1.2, 'F');
          
          doc.setTextColor(...theme.colors.textMain);
          doc.text(text, contentX + 7, listY);
          
          listY += 6;
        });

        contentY = listY + 4; 
    }

    // Cost Grid
    doc.setFillColor(...theme.colors.costBg);
    doc.setDrawColor(230, 230, 230);
    doc.roundedRect(contentX, contentY, cardWidth - 40, costBoxHeight, 2, 2, 'FD');

    const colWidth = (cardWidth - 40) / 4;
    const costY = contentY + 6;
    const valY = contentY + 14;

    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.setFont(theme.fonts.header, 'bold');

    doc.text("TRANSPORT", contentX + 5, costY);
    doc.setTextColor(0, 0, 0);
    doc.text(`$${day.estimatedCost?.transportFuel || 0}`, contentX + 5, valY);

    doc.setTextColor(150, 150, 150);
    doc.text("HOTEL", contentX + colWidth + 5, costY);
    doc.setTextColor(0, 0, 0);
    doc.text(`$${day.estimatedCost?.accommodation || 0}`, contentX + colWidth + 5, valY);

    doc.setTextColor(150, 150, 150);
    doc.text("TICKETS", contentX + (colWidth * 2) + 5, costY);
    doc.setTextColor(0, 0, 0);
    doc.text(`$${day.estimatedCost?.tickets || 0}`, contentX + (colWidth * 2) + 5, valY);

    doc.setTextColor(...theme.colors.dayBadgeText);
    doc.setFontSize(9);
    const dayTotal = (day.estimatedCost?.transportFuel || 0) + (day.estimatedCost?.accommodation || 0) + (day.estimatedCost?.tickets || 0) + (day.estimatedCost?.food || 0);
    doc.text(`$${dayTotal}`, contentX + (colWidth * 3) + 10, valY - 2);
    
    doc.setDrawColor(220, 220, 220);
    doc.line(contentX + colWidth, contentY + 3, contentX + colWidth, contentY + costBoxHeight - 3);
    doc.line(contentX + (colWidth * 2), contentY + 3, contentX + (colWidth * 2), contentY + costBoxHeight - 3);

    contentY += costBoxHeight + 5;

    // Accommodation
    if (day.accommodation) {
        doc.setFillColor(...theme.colors.hotelBg);
        doc.setDrawColor(187, 247, 208);
        doc.roundedRect(contentX, contentY, cardWidth - 40, hotelBoxHeight, 2, 2, 'FD');

        doc.setTextColor(...theme.colors.hotelText);
        doc.setFontSize(9);
        doc.setFont(theme.fonts.header, 'bold');
        doc.text("Stay:", contentX + 5, contentY + 11);
        
        const isHotelObj = typeof day.accommodation !== 'string';
        let hotelName = safeString(isHotelObj ? day.accommodation.name : day.accommodation);
        if(hotelName.length > 50) hotelName = hotelName.substring(0, 50) + '...';
        
        doc.setTextColor(0, 0, 0);
        doc.text(hotelName, contentX + 16, contentY + 11);

        // Extra details for object-type accommodations
        if (isHotelObj) {
            doc.setFontSize(8);
            doc.setFont(theme.fonts.body, 'normal');
            doc.setTextColor(...theme.colors.textLight);
            
            let extraDetails = [];
            if (day.accommodation.rating) extraDetails.push(`Rating: ${day.accommodation.rating} Stars`);
            
            const hotelPrice = day.accommodation.price || day.accommodation.estimatedCost || day.estimatedCost?.accommodation;
            if (hotelPrice) {
                extraDetails.push(`Price: $${hotelPrice}/night`);
            }
            
            if (extraDetails.length > 0) {
                doc.text(extraDetails.join('   |   '), contentX + 5, contentY + 16);
            }

            if (day.accommodation.description) {
                 let desc = safeString(day.accommodation.description);
                 if(desc.length > 80) desc = desc.substring(0, 80) + '...';
                 doc.setFontSize(7);
                 doc.setTextColor(150, 150, 150);
                 doc.text(desc, contentX + 5, contentY + 22);
            }
        }
    }

    yPos = actualY + cardHeight + 8;
  };

  // ==========================================
  // COST CALCULATIONS (For Overview & Table)
  // ==========================================
  let accCost = 0, tixCost = 0, foodCost = 0, transCost = 0, vehCost = 0, guideCost = 0, miscCost = 0;
  
  planToPrint.days?.forEach((d: any) => {
      // Accommodation
      if (typeof d.accommodation === 'object' && (d.accommodation?.price || d.accommodation?.estimatedCost)) {
          accCost += Number(d.accommodation.price || d.accommodation.estimatedCost) || 0;
      } else {
          accCost += Number(d.estimatedCost?.accommodation) || 0;
      }

      // Tickets (Check overrides first, else fallback)
      if (Array.isArray(d.activities)) {
          let dailyTix = 0;
          d.activities.forEach((act: any) => {
               if (typeof act === 'object' && (act.price || act.ticketPrice || act.cost)) {
                   dailyTix += Number(act.price || act.ticketPrice || act.cost) || 0;
               }
          });
          if (dailyTix > 0) tixCost += dailyTix;
          else tixCost += Number(d.estimatedCost?.tickets) || 0;
      } else {
          tixCost += Number(d.estimatedCost?.tickets) || 0;
      }

      foodCost += Number(d.estimatedCost?.food) || 0;
      transCost += Number(d.estimatedCost?.transportFuel) || 0;
      vehCost += Number(d.estimatedCost?.vehicleRental) || 0;
      guideCost += Number(d.estimatedCost?.guide) || 0;
      miscCost += Number(d.estimatedCost?.miscellaneous) || 0;
  });

  const grandTotal = accCost + tixCost + foodCost + transCost + vehCost + guideCost + miscCost;

  // ==========================================
  // 1. COVER PAGE
  // ==========================================
  drawSidebar();
  
  const contentStart = 75;
  yPos = 80;

  doc.setTextColor(0, 66, 49);
  doc.setFontSize(36);
  doc.setFont(theme.fonts.header, 'bold');
  
  const titleText = safeString(itinerary.title || "SRI LANKA JOURNEY");
  const titleLines = doc.splitTextToSize(titleText, 120);
  doc.text(titleLines, contentStart, yPos);
  
  yPos += (titleLines.length * 14) + 10;

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.setFont(theme.fonts.body, 'normal');
  doc.text(`${input.adults} Adults${input.children > 0 ? `, ${input.children} Children` : ''}`, contentStart, yPos);
  yPos += 8;
  doc.text(`${input.arrivalDate}  -  ${input.departureDate}`, contentStart, yPos);

  yPos += 15;
  doc.setDrawColor(249, 115, 22);
  doc.setLineWidth(1.5);
  doc.line(contentStart, yPos, contentStart + 40, yPos);

  yPos += 15;
  
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  
  const summaryText = safeString(itinerary.summary || "");
  const summaryLines = doc.splitTextToSize(summaryText, 115);
  doc.text(summaryLines, contentStart, yPos);

  // ==========================================
  // 2. OVERVIEW PAGE
  // ==========================================
  doc.addPage();
  addPageHeader(2);
  addFooter();
  yPos = 30;

  doc.setFontSize(18);
  doc.setTextColor(...theme.colors.primary);
  doc.setFont(theme.fonts.header, 'bold');
  doc.text("Trip Overview", margin, yPos);
  yPos += 12;

  const overviewData = [
    ['Travel Dates', `${input.arrivalDate || 'N/A'} to ${input.departureDate || 'N/A'}`],
    ['Travelers', `${input.adults || 0} Adults, ${input.children || 0} Children`],
    ['Duration', `${planToPrint.days?.length || 0} Days`],
    ['Vehicle', safeString(input.vehicleType || 'N/A')],
    ['Hotel Tier', `${input.hotelRating || 'N/A'} Star`],
    ['Estimated Budget', `$${input.budget || 0} USD`]
  ];

  // Dynamically add other input fields to overview if they exist
  if (input.pace) {
      overviewData.push(['Travel Pace', safeString(input.pace)]);
  }
  if (input.guide !== undefined || (input as any).guideRequired !== undefined) {
      const guideStatus = input.guide !== undefined ? input.guide : (input as any).guideRequired;
      const guideText = typeof guideStatus === 'boolean' ? (guideStatus ? 'Yes' : 'No') : safeString(guideStatus);
      overviewData.push(['Guide', guideText]);
  }
  if (input.interests && input.interests.length > 0) {
      overviewData.push(['Interests', Array.isArray(input.interests) ? input.interests.join(', ') : safeString(input.interests)]);
  }
  if (input.dietaryRequirements || (input as any).dietary) {
      overviewData.push(['Dietary Needs', safeString(input.dietaryRequirements || (input as any).dietary)]);
  }
  if (input.specialRequirements || (input as any).specialRequests) {
      overviewData.push(['Special Requests', safeString(input.specialRequirements || (input as any).specialRequests)]);
  }

  // Improved Overview Table Styling
  autoTable(doc, {
    startY: yPos,
    body: overviewData,
    theme: 'plain',
    styles: { fontSize: 11, cellPadding: 8, textColor: theme.colors.textMain, lineColor: theme.colors.border, lineWidth: 0.1 },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: theme.colors.primary, cellWidth: 50, fillColor: theme.colors.primaryLight },
      1: { textColor: theme.colors.textMain, fillColor: 255 }
    },
    margin: { left: margin, right: margin }
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  doc.setFillColor(...theme.colors.hotelBg);
  doc.setDrawColor(187, 247, 208);
  doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 25, 3, 3, 'FD');
  
  doc.setFontSize(12);
  doc.setTextColor(...theme.colors.hotelText);
  doc.text("Total Estimated Trip Cost", margin + 15, yPos + 15);
  
  doc.setFontSize(16);
  doc.setFont(theme.fonts.header, 'bold');
  doc.text(`$${grandTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, pageWidth - margin - 15, yPos + 16, { align: 'right' });

  // ==========================================
  // 3. DAILY ITINERARY (CARD STYLE)
  // ==========================================
  doc.addPage();
  addPageHeader(doc.getNumberOfPages());
  addFooter();
  yPos = 30;

  doc.setFontSize(18);
  doc.setTextColor(...theme.colors.primary);
  doc.text("Daily Itinerary", margin, yPos);
  yPos += 15;

  planToPrint.days?.forEach((day: any, index: number) => {
    drawDayCard(day, index);
  });

  // ==========================================
  // 4. COST BREAKDOWN TABLE (IMPROVED)
  // ==========================================
  doc.addPage();
  addPageHeader(doc.getNumberOfPages());
  addFooter();
  yPos = 30;

  doc.setFontSize(18);
  doc.setTextColor(...theme.colors.primary);
  doc.setFont(theme.fonts.header, 'bold');
  doc.text("Cost Breakdown (Estimated)", margin, yPos);
  yPos += 15;

  const costData = [
    ['Accommodation', `$${accCost.toFixed(2)}`],
    ['Tickets & Activities', `$${tixCost.toFixed(2)}`],
    ['Food & Dining', `$${foodCost.toFixed(2)}`],
    ['Transport (Fuel/Travel)', `$${transCost.toFixed(2)}`],
    ['Vehicle Rental', `$${vehCost.toFixed(2)}`],
    ['Guide Fees', `$${guideCost.toFixed(2)}`],
    ['Miscellaneous', `$${miscCost.toFixed(2)}`],
  ];

  // Attractive Cost Table styling
  autoTable(doc, {
    startY: yPos,
    head: [['Expense Category', 'Estimated Cost']],
    body: costData,
    foot: [['TOTAL ESTIMATED COST', `$${grandTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`]],
    theme: 'grid',
    styles: { fontSize: 11, cellPadding: 8, lineColor: theme.colors.border, lineWidth: 0.1 },
    headStyles: { fillColor: theme.colors.primary, textColor: 255, fontStyle: 'bold', fontSize: 12 },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: theme.colors.textMain },
      1: { textColor: theme.colors.primary, halign: 'right', fontStyle: 'bold' }
    },
    alternateRowStyles: { fillColor: theme.colors.costBg },
    footStyles: { fillColor: theme.colors.accent, textColor: 255, fontStyle: 'bold', fontSize: 13 },
    margin: { left: margin, right: margin }
  });

  // ==========================================
  // 5. THANK YOU PAGE
  // ==========================================
  doc.addPage();
  doc.setFillColor(...theme.colors.primaryLight);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  doc.setDrawColor(...theme.colors.primary);
  doc.setLineWidth(2);
  doc.rect(15, 15, pageWidth - 30, pageHeight - 30);

  const centerX = pageWidth / 2;
  const centerY = pageHeight / 2;

  doc.setTextColor(...theme.colors.primary);
  doc.setFontSize(36);
  doc.setFont(theme.fonts.header, 'bold');
  doc.text("THANK YOU", centerX, centerY - 15, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.setFont(theme.fonts.body, 'normal');
  doc.text("We hope you enjoy your Sri Lankan Adventure!", centerX, centerY + 5, { align: 'center' });

  // Save
  doc.save(`SriLanka_Trip_${new Date().toISOString().split('T')[0]}.pdf`);
};